
datasource:
  url: jdbc:mysql://127.0.0.1:3306/enterprise
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver

generator:
  company-name: enterprise
  project-name: enterprise
  project-path: /Users/jiahao.zhang/Documents/trash/code-generator/
  test-path: /Users/jiahao.zhang/Documents/trash/code-generator/
  po-name: enterprise #testPO.java
  table-name: enterprise
  enable:
    po-domain: true
    controller: true
    use-case: true
    repo-interface: true
    repo-impl: true
    service: true
    jpa-repo: true
    test-builder: true

