
datasource:
  url: jdbc:mysql://127.0.0.1:3306/settlement_dev
  username: root
  password: root
  driver-class-name: com.mysql.cj.jdbc.Driver

generator:
  company-name: faas
  project-name: test
  project-path: /Users/jiahao.zhang/Documents/trash/test-code-generator/
  test-path: /Users/jiahao.zhang/Documents/trash/test-code-generator/
  po-name: invoice_detail #testPO.java
  table-name: invoice_detail
  enable:
    po-domain: false
    controller: false
    use-case: false
    repo-interface: false
    repo-impl: false
    service: false
    jpa-repo: false
    test-builder: true

